export const investigation = {
  nodes: [
    { id: 'incident-4821', label: 'Incident 4821', data: { role: 'alert', group: 'case' } },
    { id: 'alert-login', label: 'Impossible login', data: { role: 'alert', group: 'case' } },
    { id: 'alert-transfer', label: 'Unusual transfer', data: { role: 'alert', group: 'case' } },
    { id: 'alert-device', label: 'New device', data: { role: 'alert', group: 'case' } },
    { id: 'identity-alice', label: 'Alice Chen', data: { role: 'person', group: 'identity' } },
    { id: 'identity-omar', label: 'Omar Rahman', data: { role: 'person', group: 'identity' } },
    { id: 'identity-vendor', label: 'Vendor operator', data: { role: 'person', group: 'identity' } },
    { id: 'identity-intruder', label: 'Unknown actor', data: { role: 'person', group: 'identity' } },
    { id: 'identity-analyst', label: 'Maya · analyst', data: { role: 'person', group: 'operations' } },
    { id: 'service-auth', label: 'Authentication', data: { role: 'service', group: 'platform' } },
    { id: 'service-payments', label: 'Payments', data: { role: 'service', group: 'platform' } },
    { id: 'service-gateway', label: 'Payment gateway', data: { role: 'service', group: 'platform' } },
    { id: 'service-case', label: 'Case service', data: { role: 'service', group: 'platform' } },
    { id: 'service-notify', label: 'Notifications', data: { role: 'service', group: 'platform' } },
    { id: 'service-api', label: 'Partner API', data: { role: 'service', group: 'platform' } },
    { id: 'device-laptop', label: 'Alice · laptop', data: { role: 'device', group: 'devices' } },
    { id: 'device-mobile', label: 'Omar · mobile', data: { role: 'device', group: 'devices' } },
    { id: 'device-terminal', label: 'Vendor terminal', data: { role: 'device', group: 'devices' } },
    { id: 'device-proxy', label: 'Proxy host', data: { role: 'device', group: 'devices' } },
    { id: 'device-vpn', label: 'Corporate VPN', data: { role: 'device', group: 'devices' } },
    { id: 'data-accounts', label: 'Accounts', data: { role: 'data', group: 'records' } },
    { id: 'data-sessions', label: 'Sessions', data: { role: 'data', group: 'records' } },
    { id: 'data-ledger', label: 'Ledger', data: { role: 'data', group: 'records' } },
    { id: 'data-sanctions', label: 'Sanctions list', data: { role: 'data', group: 'records' } },
    { id: 'data-audit', label: 'Audit trail', data: { role: 'data', group: 'records' } },
    { id: 'place-dubai', label: 'Dubai', data: { role: 'place', group: 'places' } },
    { id: 'place-singapore', label: 'Singapore', data: { role: 'place', group: 'places' } },
    { id: 'place-london', label: 'London', data: { role: 'place', group: 'places' } },
    { id: 'entity-merchant', label: 'Meridian Supplies', data: { role: 'entity', group: 'counterparties' } },
    { id: 'entity-beneficiary', label: 'Northstar Trading', data: { role: 'entity', group: 'counterparties' } },
    { id: 'entity-ip', label: '203.0.113.42', data: { role: 'entity', group: 'evidence' } },
    { id: 'entity-domain', label: 'portal-check.example', data: { role: 'entity', group: 'evidence' } },
    { id: 'group-operations', label: 'Operations', data: { role: 'group', group: 'teams' } },
    { id: 'group-fraud', label: 'Fraud team', data: { role: 'group', group: 'teams' } },
    { id: 'group-risk', label: 'Risk team', data: { role: 'group', group: 'teams' } },
    { id: 'entity-ticket', label: 'Ticket FR-2048', data: { role: 'entity', group: 'case' } },
  ],
  edges: [
    { source: 'incident-4821', target: 'alert-login', data: { role: 'signal' } },
    { source: 'incident-4821', target: 'alert-transfer', data: { role: 'signal' } },
    { source: 'incident-4821', target: 'alert-device', data: { role: 'signal' } },
    { source: 'incident-4821', target: 'entity-ticket', data: { role: 'relationship' } },
    { source: 'alert-login', target: 'identity-alice', data: { role: 'risk' } },
    { source: 'alert-transfer', target: 'identity-omar', data: { role: 'risk' } },
    { source: 'alert-device', target: 'identity-intruder', data: { role: 'risk' } },
    { source: 'identity-alice', target: 'device-laptop', data: { role: 'association' } },
    { source: 'identity-omar', target: 'device-mobile', data: { role: 'association' } },
    { source: 'identity-vendor', target: 'device-terminal', data: { role: 'association' } },
    { source: 'identity-intruder', target: 'device-proxy', data: { role: 'association' } },
    { source: 'device-laptop', target: 'service-auth', data: { role: 'flow' } },
    { source: 'device-mobile', target: 'service-auth', data: { role: 'flow' } },
    { source: 'device-terminal', target: 'service-api', data: { role: 'flow' } },
    { source: 'device-proxy', target: 'entity-ip', data: { role: 'association' } },
    { source: 'device-vpn', target: 'service-auth', data: { role: 'flow' } },
    { source: 'entity-ip', target: 'place-singapore', data: { role: 'association' } },
    { source: 'entity-domain', target: 'entity-ip', data: { role: 'dependency' } },
    { source: 'service-auth', target: 'data-sessions', data: { role: 'dependency' } },
    { source: 'service-auth', target: 'data-accounts', data: { role: 'dependency' } },
    { source: 'service-auth', target: 'service-payments', data: { role: 'flow' } },
    { source: 'service-payments', target: 'service-gateway', data: { role: 'flow' } },
    { source: 'service-gateway', target: 'data-ledger', data: { role: 'dependency' } },
    { source: 'service-api', target: 'service-gateway', data: { role: 'flow' } },
    { source: 'service-payments', target: 'data-sanctions', data: { role: 'dependency' } },
    { source: 'service-payments', target: 'data-audit', data: { role: 'dependency' } },
    { source: 'service-case', target: 'data-audit', data: { role: 'dependency' } },
    { source: 'service-case', target: 'service-notify', data: { role: 'flow' } },
    { source: 'entity-merchant', target: 'service-api', data: { role: 'flow' } },
    { source: 'service-gateway', target: 'entity-beneficiary', data: { role: 'flow' } },
    { source: 'entity-merchant', target: 'place-dubai', data: { role: 'association' } },
    { source: 'entity-beneficiary', target: 'place-london', data: { role: 'association' } },
    { source: 'device-terminal', target: 'place-dubai', data: { role: 'association' } },
    { source: 'device-mobile', target: 'place-london', data: { role: 'association' } },
    { source: 'identity-alice', target: 'data-accounts', data: { role: 'membership' } },
    { source: 'identity-omar', target: 'data-accounts', data: { role: 'membership' } },
    { source: 'identity-analyst', target: 'entity-ticket', data: { role: 'relationship' } },
    { source: 'identity-analyst', target: 'group-fraud', data: { role: 'membership' } },
    { source: 'group-fraud', target: 'group-risk', data: { role: 'relationship' } },
    { source: 'group-risk', target: 'group-operations', data: { role: 'relationship' } },
    { source: 'group-operations', target: 'service-case', data: { role: 'dependency' } },
    { source: 'entity-ticket', target: 'service-case', data: { role: 'relationship' } },
    { source: 'alert-transfer', target: 'entity-merchant', data: { role: 'risk' } },
    { source: 'alert-transfer', target: 'entity-beneficiary', data: { role: 'risk' } },
    { source: 'alert-login', target: 'entity-domain', data: { role: 'risk' } },
  ],
};
